FROM postgres
COPY pg_hba.conf /usr/share/postgresql/9.6/
COPY postgresql.conf /usr/share/postgresql/9.6/
ADD init-db.sql /docker-entrypoint-initdb.d/init-db.sql
ENV POSTGRES_USER gordonuser
ENV POSTGRES_DB ddev