version: "3.1"

services:
  database:
    image: leanderjanssen/db
    networks:
    - back-tier

  api:
    image: leanderjanssen/api
    networks:
    - front-tier
    - back-tier

  ui:
    image: leanderjanssen/ui
    ports:
    - "3000:3000"
    networks:
    - front-tier

networks:
  front-tier:
  back-tier:
